#!/bin/sh -e
# Create/destroy temporary chroots

log() {
    printf '\033[31;1m->\033[m %s.\n' "$@"
}

cd "${cac_dir:=$KISS_ROOT${XDG_CACHE_HOME:-$HOME/.cache}/kiss}"

[ -f kiss-chroot.tar.xz ] || {
    log "Downloading chroot tarball"

    url=https://github.com/kisslinux/repo/releases/download/1.9.11/
    wget "$url/kiss-chroot.tar.xz"
}

[ -d kiss-chroot ] || {
    log "Extracting chroot"
    tar xf kiss-chroot.tar.xz
}

log "Creating temporary chroot"
cp -a kiss-chroot "chroot-$$"

log "Entering chroot"
su -c "kiss-chroot chroot-$$; rm -rf chroot-$$"
