#!/bin/sh
# Generate sources for rust packages.

[ "$1" ] || {
    printf 'usage: kiss-cargo-urlgen [crate-ver] [crate-ver]\n'
    exit 1
}

for crate in "$@"; do
    printf 'https://static.crates.io/crates/%s/%s.crate vendor\n' \
        "${crate%-*}" "$crate"
done
