#!/bin/sh -e
# List packages which aren't present in any repository.

cd "$KISS_ROOT/var/db/kiss/installed"

kiss s * | while read -r path; do
    pkg=${path##*/}

    case $seen in *" $pkg "*)
        continue
    esac

    case $path in "$PWD/$pkg")
        printf '%s\n' "$pkg"
    esac

    seen="$seen $pkg "
done


