#!/bin/sh -e

[ -z "$1" ] && exit 1
for dir in "$@" ; do
	mkdir -p "$dir"
	for file in version sources build; do
		:> "$dir/$file"
	done
	chmod +x "$dir/build"
	printf "\033[1;33m->\033[0;00m Added empty package \033[1;36m$dir\033[0;00m to $PWD/$dir\n"
done
