#!/bin/sh -ef
# Remove all packages except for the base.
#
# Disable word-splittng warnings as they're safe here.
# shellcheck disable=SC2046

set --

while read -r pkg _; do
    case $pkg in
        baselayout|binutils|bison|busybox|bzip2|curl|flex|gcc|git|\
        gzip|kiss|libressl|linux-headers|m4|make|musl|pkgconf|rsync|\
        xz|zlib) ;;

        *) set -- "$@" "$pkg" ;;
    esac
done <<EOF
$(kiss l)
EOF

[ "$1" ] && {
    printf 'WARNING: This will remove \033[1m%s\033[m package(s).\n' "$#"
    printf 'Continue? [Enter/Ctrl+C]\n'
    read -r _ && KISS_FORCE=1 kiss r "$@"
}
