#!/bin/sh -ef
#
# kiss-manifest-tree - Display all files owned by a package.

kiss l "${1:-null}"

db_dir=$KISS_ROOT/var/db/kiss/installed/${1:-null}

printf '%s\n' "[$1]:"
tree -C --fromfile "$db_dir/manifest" | tail -n +2
