#!/bin/sh -e
#
# kiss-orphans - List orphaned packages.

cd "$KISS_ROOT/var/db/kiss/installed/"

for pkg in *; do
    case $pkg in
        baseinit|baselayout|gcc|pkgconf|e2fsprogs|musl|\
        make|busybox|bzip2|grub|automake|kiss|rsync|git)
            continue
    esac

    grep -q "^$pkg$" ./*/depends || printf '%s\n' "$pkg"
done
