#!/bin/sh -e
# List orphaned packages

cd "$KISS_ROOT/var/db/kiss/installed/"

for pkg in *; do
    case $pkg in
        # Exemptions for orphans which aren't really
        # orphans. Exclude them from the list.
        baseinit|baselayout|gcc|e2fsprogs|musl|\
        make|busybox|bzip2|grub|kiss|git)
            continue
    esac

    (
        grep -q "^$pkg$" ./*/depends || printf '%s\n' "$pkg"
    ) &
done | sort
wait
