#!/bin/sh -e
# Display packages which depend on package.

# Ignore shellcheck as we want the warning's behavior.
# shellcheck disable=2015
[ "$1" ] && kiss l "${1:-null}" >/dev/null || {
    printf 'usage: kiss-revdepends [pkg]\n'
    exit 1
}

# 'cd' to the database directory as a simple way of
# stripping the path and performing a 'basename'.
cd "$KISS_ROOT/var/db/kiss/installed"

# Use a simple 'grep' to display packages depending on '$1'.
grep "^$1" -- */depends
