#!/bin/sh -ef
#
# Disable word-splittng warnings as they're safe here.
# shellcheck disable=SC2046
#
# kiss-reset: Remove all packages except for the base.

set --

kiss l | while read -r pkg _; do
    case $pkg in
        baselayout|binutils|bison|busybox|bzip2|curl|flex|gcc|git|\
        gzip|kiss|libelf|libressl|linux-headers|m4|make|musl|perl|\
        pkgconf|rsync|xz|zlib) ;;

        *) set -- "$@" "$pkg" ;;
    esac
done

[ "$1" ] && {
    printf 'WARNING: This will remove \033[1m%s\033[m package(s).\n' "$#"
    printf 'Continue? [Enter/Ctrl+C]\n'
    read -r _ && KISS_FORCE=1 kiss r "$@"
}
