#!/bin/sh -ef
#
# kiss-export - Turn an installed package into a KISS tarball.

kiss l "${1:-null}" >/dev/null

# Grab the package's version..
read -r ver rel 2>/dev/null < \
    "$KISS_ROOT/var/db/kiss/installed/$1/version"

# Reset the argument list.
pkg=$1
set --

# Construct the argument list using each file.
while read -r file || [ "$file" ]; do
    [ -d "$KISS_ROOT/$file" ] || set -- "$@" ".$file"
done < "$KISS_ROOT/var/db/kiss/installed/$pkg/manifest"

# Turn the list of files back into a package.
tar czf "$pkg#$ver-$rel.tar.gz" -C / -- "$@"

printf 'tarball created in %s\n' "$PWD/$pkg#$ver-$rel.tar.gz"
