#!/bin/sh

# kiss-rrevdepends (repo-revdepends)
# kiss-revdepends, execpt for packages in your $KISS_PATH

for repo in $(echo $KISS_PATH | tr ':' ' ')
do
	for pkg in $repo/*
	do
		(
			if grep -sq "$1" "$pkg/depends" ; then
				echo $pkg
			fi
		) &
	done
done
wait
