#!/bin/sh -ef
# Display all files owned by a package

# Ignore shellcheck as we want the warning's behavior.
# shellcheck disable=2015
[ "$1" ] && kiss l "${1:-null}" >/dev/null || {
    printf 'usage: kiss-manifest [pkg]\n'
    exit 1
}

cat "$KISS_ROOT/var/db/kiss/installed/$1/manifest" 2>/dev/null
