#!/bin/sh -e
# List packages which aren't present in any repository.

cd "$KISS_ROOT/var/db/kiss/installed"

for pkg in *; do
    i=1

    kiss s "$pkg" | while read -r line; do
        case $i-$line in ("1-$PWD/$pkg")
            printf '%s\n' "$pkg"
            continue
        esac

        i=$((i + 1))
    done
done
