#!/bin/sh -ef
# Display a package's dependencies

# CRUX style usage using the current directory as the name of the package to be
# operated on.
[ "$1" ] || {
    set -- "${PWD##*/}"
}

# Ignore shellcheck as we want the warning's behavior.
# shellcheck disable=2015
kiss l "${1:-null}" >/dev/null || {
    printf 'usage: kiss-depends [pkg]\n'
    exit 1
}

cat "$KISS_ROOT/var/db/kiss/installed/$1/depends" 2>/dev/null
