#!/bin/sh -e
# Remove all packages except for the base

set --

for pkg in "$KISS_ROOT/var/db/kiss/installed/"*; do
    pkg=${pkg##*/}

    case $pkg in
        baselayout|binutils|bison|busybox|bzip2|curl|flex|gcc|git|\
        gzip|kiss|libressl|linux-headers|m4|make|musl|pkgconf|xz|zlib) ;;

        *) set -- "$@" "$pkg" ;;
    esac
done

[ "$1" ] && {
    printf 'WARNING: This will remove \033[1m%s\033[m package(s).\n' "$#"
    printf 'Continue? [Enter/Ctrl+C]\n'
    read -r _ && KISS_FORCE=1 kiss r "$@"
}
