#!/bin/sh -e

# shellcheck disable=SC2015
# shellcheck disable=SC2059

out() { printf "=> $1\n" ;}
die() { printf "error: $1\n" ; exit 1 ;}
[ -z "$1" ] && { out "${0##*/} <package> [version] [sources]"; exit ;}
[ -d "$1" ] && die "Package $1 already exists"

mkdir -p "$1" || die "Couldn't create directory in $PWD"

out "Populating build file" ; {
printf "#!/bin/sh -e\n" > "$1/build"
chmod +x "$1/build"
}

[ -n "$2" ] && {
	out "Populating version file with '${2%% *} 1'"
	printf "${2%% *} 1\n" > "$1/version"
} || :> "$1/version"

[ -n "$3" ] && {
	out "Populating sources file with '$3'"
	printf "$3\n" > "$1/sources"
} || :> "$1/version"
