#!/bin/sh
# shellcheck source=/dev/null
#
# This is a simple package manager written in POSIX shell for use
# in KISS Linux (https://k1ss.org).
#
# Created by Dylan Araps.

log() {
    printf '%b%s %b%s%b %s\n' \
        "$lcol" "${3:-->}" "${lclr}${2:+$lcol2}" "$1" "$lclr" "$2" >&2
}

war() {
    log "$1" "$2" "${3:-WARNING}"
}

die() {
    log "$1" "$2" "${3:-ERROR}"
    exit 1
}

contains() {
    case " $1 " in *" $2 "*) return 0; esac; return 1
}

prompt() {
    [ "$1" ] && log "$1"

    log "Continue?: Press Enter to continue or Ctrl+C to abort here"

    [ "$KISS_PROMPT" = 0 ] || read -r _
}

as_root() {
    [ "$uid" = 0 ] || log "Using '${su:=su}' (to become ${user:=root})"

    case ${su##*/} in
        doas | sudo | sls)
            "$su" -u "$user" -- env "$@"
        ;;

        su)
            "$su" -c "env $* <&3" "$user" 3<&0 </dev/tty
        ;;

        *)
            die "Invalid KISS_SU value: $su (valid: doas, sudo, sls, su)"
        ;;
    esac
}

file_owner() {
    read -r _ _ user _ <<EOF
$(ls -ld "$1")
EOF

    id -u "${user:=root}" >/dev/null 2>&1 || user=root
}

find_replace() {
    while IFS= read -r _line; do
        case $_line in
            "$1")
                printf '%s\n' "$2"
            ;;

            *)
                printf '%s\n' "$_line"
            ;;
        esac
    done < "$3" |

    sort -r > "$tmp_dir/.sed"

    mv -f "$tmp_dir/.sed" "$3"
}

run_hook() {
    # Provide a default post-build hook to remove files and directories
    # for things we don't support out of the box. One can simply define
    # their own hook to override this behavior.
    set -- "${1:-null}" "${2:-null}" "${3:-null}"

    case ${KISS_HOOK:--}$1 in
        -post-build)
            rm -rf \
                "$3/usr/share/gettext" \
                "$3/usr/share/polkit-1" \
                "$3/usr/share/locale" \
                "$3/usr/share/info"
        ;;

        [!-]*)
            TYPE=$1 PKG=$2 DEST=$3 . "$KISS_HOOK"
        ;;
    esac
}

decompress() {
    case ${1##*.} in
        bz2)      bzip2 -dc ;;
        lzma)     lzma  -dc ;;
        lz)       lzip  -dc ;;
        tar)      cat       ;;
        tgz | gz) gzip  -dc ;;
        txz | xz) xz    -dc ;;
        zst)      zstd  -dc ;;
    esac < "$1"
}

sh256() {
    # There's no standard utility to generate sha256 checksums.
    # This unifies various tools using the first available.
    [ -e "$1" ] || return 0

    hash=$(
        sha256sum               "$1" ||
        sha256 -r               "$1" ||
        openssl dgst -sha256 -r "$1" ||
        shasum -a 256           "$1" ||
        digest -a sha256        "$1"
    ) 2>/dev/null

    printf '%s\n' "${hash%% *}"
}

pkg_owner() {
    pkg_owner=$(grep "$@") && {
        pkg_owner=${pkg_owner%/*}
        pkg_owner=${pkg_owner##*/}
    }
}

pkg_lint() {
    pkg_find "$1"
    cd "$repo_dir"

    read -r _ release 2>/dev/null < version ||
        die "Version file not found"

    [ "$release" ] ||
        die "$1" "Release field not found in version file"

    [ -x build ] ||
        die "$1" "Build file not found or not executable"

    [ -f sources ] ||
        war "$1" "Sources file not found"
}

pkg_find() {
    # Figure out which repository a package belongs to by searching for
    # directories matching the package name in $KISS_PATH/*.
    _query=$1
    _paths=${2:-"$KISS_PATH:$sys_db"}
    _print=$3
    _type=${4:--d}

    IFS=:
    set --

    # Globbing is disabled, splitting is intentional.
    for _path in $_paths; do
        set +f

        # Globbing enabled for search.
        for _path2 in "$_path"/${_query%%/*}; do
            test "$_type" "$_path2" &&
                set -f -- "$@" "$_path2"
        done
    done

    unset IFS
    repo_dir=$1

    [ "$1" ] || {
        log "Package '$_query' not in any repository"
        return 1
    }

    [ -z "$_print" ] ||
        printf '%s\n' "$@"
}

pkg_list() {
    [ "$1" ] || {
        set +f
        set -f -- "$sys_db/"*
    }

    for _pkg do
        [ -d "$sys_db/${_pkg##*/}" ] || {
            log "${_pkg##*/}" "not installed"
            return 1
        }

        read -r _ver 2>/dev/null < "$sys_db/${_pkg##*/}/version" ||
            _ver=null

        printf '%s\n' "${_pkg##*/} $_ver"
    done
}

pkg_cache() {
    # Find the tarball of a package using a glob. Use the first found match
    # of '<pkg_name>#<pkg_version><pkg_release>.tar.*'.
    pkg_find "$1"

    read -r version release 2>/dev/null < "$repo_dir/version"

    set +f
    set -f -- "$bin_dir/$1#$version-$release.tar."*

    tar_file=$1

    [ -f "$tar_file" ]
}

pkg_sources() {
    # Download any remote package sources. The existence of local files is
    # also checked.
    pkg_find "$1"

    [ -f "$repo_dir/sources" ] || return 0

    log "$1" "Fetching sources"
    mkdir -p "$src_dir/$1"
    cd "$src_dir/$1"

    while read -r src dest || [ "$src" ]; do
        if [ -z "${src##\#*}" ]; then
            continue

        elif [ -z "${src##git+*}" ]; then
            printf 'found git      %s\n' "${src##git+}"

        elif [ -f "${src##*/}" ]; then
            printf 'found cached   %s\n' "${src##*/}"

        elif [ -z "${src##*://*}" ]; then
            printf 'downloading %s\n' "$src"

            curl "$src" -fLo "${src##*/}" || {
                rm -f "${src##*/}"
                die "$1" "Failed to download $src"
            }

        elif [ -e "$repo_dir/$src" ]; then
            printf 'found relative %s\n' "$src"

        elif [ -e "/$src" ]; then
            printf 'found absolute %s\n' "$src"

        else
            die "$1" "No local file '$src'"
        fi
    done < "$repo_dir/sources"
}

pkg_extract() {
    # Extract all source archives to the build directory and copy over any
    # local repository files.
    pkg_find "$1"

    [ -f "$repo_dir/sources" ] || return 0

    log "$1" "Extracting sources"

    while read -r src dest || [ "$src" ]; do
        mkdir -p "$mak_dir/$1/$dest" && cd "$mak_dir/$1/$dest"

        case $src in
            \#* | '')
                # Comments and blank lines.
            ;;

            git+*)
                # Split the source into URL + OBJECT (branch or commit).
                url=${src##git+} com=${url##*[@#]} com=${com#${url%[#@]*}}

                # Shallow clone branches, commits or default branch.
                log "$1" "Cloning ${url%[#@]*}"; {
                    git init
                    git remote add origin "${url%[#@]*}"
                    git fetch --tags --depth=1 origin "$com" || git fetch --tags
                    git checkout "${com:-FETCH_HEAD}"
                } || die "$1" "Failed to clone $src"
            ;;

            *://*.tar|*://*.tar.??|*://*.tar.???|*://*.tar.????|*://*.t?z)
                decompress "$src_dir/$1/${src##*/}" \
                    > "$tmp_dir/.tar"

                tar xf "$tmp_dir/.tar" ||
                    die "$1" "Couldn't extract ${src##*/}"

                # Iterate over all directories in the first level of the
                # tarball's manifest. This does the equivalent to GNU tar's
                # '--strip-components 1' in a portable way.
                tar tf "$tmp_dir/.tar" | while IFS=/ read -r dir _; do
                    # Handles tarballs with './' as top-level directory.
                    [ -d "${dir#.}" ] || continue

                    # Avoid naming conflicts.
                    mv -f "$dir" "$pid-$dir"

                    # First attempt to move all files up a directory level,
                    # if any files/directories fail (due to mv's lack of
                    # directory merge capability), simply do the exercise
                    # again and copy-merge the remaining files/directories.
                    #
                    # We can't use '-exec {} +' with any arguments between
                    # the '{}' and '+' as this is not POSIX. We must also
                    # use '$0' and '$@' to reference all arguments.
                    {
                        find "$pid-$dir/." ! -name . -prune \
                            -exec sh -c 'mv -f "$0" "$@" .' {} + ||

                        find "$pid-$dir/." ! -name . -prune \
                            -exec sh -c 'cp -fRp "$0" "$@" .' {} +
                    } 2>/dev/null

                    # Clean up after ourselves.
                    rm -rf "$pid-$dir"
                done

                # Clean up after ourselves.
                rm -f "$tmp_dir/.tar"
            ;;

            *://*.zip)
                unzip "$src_dir/$1/${src##*/}" ||
                    die "$1" "Couldn't extract ${src##*/}"
            ;;

            *)
                # Local directory (relative).
                if [ -d "$repo_dir/$src" ]; then
                    cp -Rf "$repo_dir/$src/." .

                # Local directory (absolute).
                elif [ -d "/$src" ]; then
                    cp -Rf "/$src/." .

                # Local file (relative).
                elif [ -f "$repo_dir/$src" ]; then
                    cp -f "$repo_dir/$src" .

                # Local file (absolute).
                elif [ -f "/$src" ]; then
                    cp -f "/$src" .

                # Remote file.
                elif [ -f "$src_dir/$1/${src##*/}" ]; then
                    cp -f "$src_dir/$1/${src##*/}" .

                else
                    die "$1" "file $src not found"
                fi
            ;;
        esac
    done < "$repo_dir/sources"
}

pkg_depends() {
    # Resolve all dependencies and generate an ordered list. The deepest
    # dependencies are listed first and then the parents in reverse order.
    contains "$deps" "$1" || {
        pkg_find "$1" 2>/dev/null ||:

        # Recurse through the dependencies of the child packages.
        [ -f "$repo_dir/depends" ] &&
            while read -r dep _ || [ "$dep" ]; do
                case $dep in
                    [!#]*)
                        pkg_list "$dep" >/dev/null 2>&1 ||
                            pkg_depends "$dep"
                    ;;
                esac
            done < "$repo_dir/depends"

        # After child dependencies are added to the list,
        # add the package which depends on them.
        [ "$2" = explicit ] || deps="$deps $1 "
    }
}

pkg_strip() {
    # Strip package binaries and libraries. This saves space on the system as
    # well as on the tarballs we ship for installation.
    [ -f "$mak_dir/$pkg/nostrip" ] || [ "$KISS_STRIP" = 0 ] && return

    log "$1" "Stripping binaries and libraries"

    # Strip only files matching the below ELF types. This uses 'od' to print
    # the first 18 bytes of the file. This is the location of the ELF header
    # (up to the ELF type) and contains the type information we need.
    #
    # Static libraries (.a) are in reality AR archives which contain ELF
    # objects. We simply read from the same 18 bytes and assume that the AR
    # header equates to an archive containing objects (.o).
    #
    # Example ELF output ('003' is ELF type):
    # 0000000 177   E   L   F 002 001 001  \0  \0  \0  \0  \0  \0  \0  \0  \0
    # 0000020 003  \0
    # 0000022
    #
    # Example AR output (.a):
    # 0000000   !   <   a   r   c   h   >  \n   /
    # 0000020
    # 0000022
    find "$pkg_dir/$1" -type f | while read -r file; do
        case $(od -A o -t c -N 18 "$file") in
            # REL (object files (.o), static libraries (.a)).
            *177*E*L*F*0000020\ 001\ * | *\!*\<*a*r*c*h*\>*)
                strip -g -R .comment -R .note "$file"
                printf 'stripped debug .%s\n' "${file##"$pkg_dir/$1"}"
            ;;

            # EXEC (binaries), DYN (shared libraries).
            # Shared libraries keep global symbols in a separate ELF section
            # called '.dynsym'. '--strip-all/-s' does not touch the dynamic
            # symbol entries which makes this safe to do.
            *177*E*L*F*0000020\ 00[23]\ *)
                strip -s -R .comment -R .note "$file"
                printf 'stripped all   .%s\n' "${file##"$pkg_dir/$1"}"
            ;;
        esac
    done 2>/dev/null ||:
}

pkg_fix_deps() {
    # Dynamically look for missing runtime dependencies by checking each
    # binary and library with 'ldd'. This catches any extra libraries and or
    # dependencies pulled in by the package's build suite.
    log "$1" "Looking for dependencies (using ${elf_cmd##*/})"

    cd "$pkg_dir/$1/$pkg_db/$1"

    set +f
    set -f -- "$sys_db/"*/manifest

    : >> depends

    find "$pkg_dir/${PWD##*/}/" -type f 2>/dev/null |

    while read -r file; do
        case ${elf_cmd##*/} in
            *readelf)
                "$elf_cmd" -d "$file"
            ;;

            *)
                ldd -- "$file"
            ;;
        esac 2>/dev/null |

        while read -r line; do
            case $line in
                *NEEDED*\[*\] | *'=>'*)
                    # readelf: 0x0000 (NEEDED) Shared library: [libjson-c.so.5]
                    line=${line##*[}
                    line=${line%%]*}

                    # ldd:     libjson-c.so.5 => /lib/libjson-c.so.5 ...
                    line=${line##*=> }
                    line=${line%% *}

                    # Skip files owned by libc and POSIX.
                    case ${line##*/} in
                        ld-*           |\
                        lib[cm].so*    |\
                        libdl.so*      |\
                        libpthread.so* |\
                        librt.so*      |\
                        libtrace.so*   |\
                        libxnet.so*    |\
                        ldd)
                            continue
                        ;;

                        *)
                              pkg_owner -l "/${line#/}\$" manifest ||
                            ! pkg_owner -l "/${line#/}\$" "$@" &&
                                continue

                            printf '%s\n' "$pkg_owner"
                        ;;
                    esac
                ;;
            esac
        done ||:
    done |

    sort -uk1,1 depends - > "$tmp_dir/.fixdeps"

    diff -U 3 depends - < "$tmp_dir/.fixdeps" ||:

    mv -f "$tmp_dir/.fixdeps" depends

    [ -s depends ] || rm -f depends
}

pkg_manifest() (
    # This function runs as a sub-shell to avoid having to 'cd' back to the
    # prior directory before being able to continue.
    cd "${2:-"$pkg_dir"}/$1"

    # find: Print all files and directories and append '/' to directories.
    # sed:  Remove the first character in each line (./dir -> /dir) and
    #       remove all lines which only contain '.'.
    find . -type d -exec printf '%s/\n' {} + -o -print |

    sort -r |

    sed '/^\.\/$/d;ss.ss' > "${2:-"$pkg_dir"}/$1/$pkg_db/$1/manifest"
)

pkg_manifest_verify() {
    # Ensure that everything listed in the manifest exists in the tarball.
    while read -r line; do
        [ -h "./$line" ] ||
        [ -e "./$line" ] ||
            man_err="$man_err$line, "
    done < "$1"

    [ -z "$man_err" ] ||
        die "$pkg" "Files in manifest missing from tarball: ${man_err%, }"
}

pkg_etcsums() (
    # This function runs as a sub-shell to avoid having to 'cd' back to the
    # prior directory before being able to continue.
    [ -d "$pkg_dir/$1/etc" ] || return 0

    cd "$pkg_dir/$1"

    # This can't be a simple 'find -exec' as 'sh256' is a shell function
    # and not a real command of any kind. This is the shell equivalent.
    find etc -type f | sort | while read -r line; do
        sh256 "$line"
    done > "$pkg_dir/$1/$pkg_db/$1/etcsums"
)

pkg_tar() (
    pkg_find "$1"

    read -r version release < "$repo_dir/version"

    # Avoid tar -C (not portable).
    cd "$pkg_dir/$1"

    # Create a tarball from the contents of the built package.
    tar cf - . | case ${KISS_COMPRESS:-gz} in
        bz2)  bzip2 -z ;;
        gz)   gzip -6  ;;
        lzma) lzma -z  ;;
        lz)   lzip -z  ;;
        xz)   xz -zT 0 ;;
        zst)  zstd -z  ;;
    esac > "$bin_dir/$1#$version-$release.tar.${KISS_COMPRESS:-gz}"

    run_hook post-package "$1"
)

pkg_build() {
    # Mark packages passed on the command-line separately from those
    # detected as dependencies. We need to treat explicitly passed packages
    # differently from those pulled in as dependencies.
    #
    # This also resolves all dependencies and stores the result in '$deps'.
    # Any duplicates are also filtered out.
    for pkg do
        contains "$explicit" "$pkg" || {
            pkg_depends "$pkg" explicit
            explicit="$explicit $pkg "
        }
    done

    # If not an update, ignore the cache and build everything given
    # on the command-line. If this is an update, use the cache.
    [ "$pkg_update" ] || explicit_build=$explicit

    # If an explicit package is a dependency of another explicit package,
    # remove it from the explicit list as it needs to be installed as a
    # dependency.
    for pkg do
        contains "$deps" "$pkg" ||
            explicit2=" $explicit2 $pkg "
    done
    explicit=$explicit2

    # Intentional, globbing disabled.
    # shellcheck disable=2046,2086
    set -- $deps $explicit

    [ "$#" -gt 1 ] || [ "$pkg_update" = 1 ] &&
        prompt "Building $*"

    for pkg do pkg_lint "$pkg"; done

    log "Checking for pre-built dependencies"

    # Install any pre-built dependencies if they exist in the binary
    # directory and are up to date.
    for pkg do
        ! contains "$explicit_build" "$pkg" && pkg_cache "$pkg" && {
            log "$pkg" "Installing binary from cache"

            # False positive.
            # shellcheck disable=2030
            (
                KISS_FORCE=1
                args i "$tar_file"
            )

            # Remove the now installed package from the build list.
            shift
        }
    done

    for pkg do pkg_sources "$pkg"; done
    for pkg do pkg_verify  "$pkg"; done

    # Finally build and create tarballs for all passed packages and
    # dependencies.
    for pkg do
        log "$pkg" "Building package ($((in+=1))/$#)"

        run_hook pre-extract "$pkg" "$pkg_dir/$pkg"
        pkg_extract "$pkg"
        pkg_find "$pkg"

        # Install built packages to a directory under the package name to
        # avoid collisions with other packages.
        mkdir -p "$pkg_dir/$pkg/$pkg_db" "$mak_dir/$pkg"
        cd "$mak_dir/$pkg"

        # Log the version so we can pass it to the package build file.
        read -r build_version _ < "$repo_dir/version"

        log "$pkg" "Starting build"
        run_hook pre-build "$pkg" "$pkg_dir/$pkg"

        # Call the build script, log the output to the terminal and to a file.
        # There's no PIPEFAIL in POSIX shelll so we must resort to tricks like
        # killing the script ourselves.
        { "$repo_dir/build" "$pkg_dir/$pkg" "$build_version" 2>&1 || {
            log "$pkg" "Build failed"
            log "$pkg" "Log stored to $log_dir/$pkg-$time-$pid"
            run_hook build-fail "$pkg" "$pkg_dir/$pkg"
            pkg_clean
            kill 0
        } } | tee "$log_dir/$pkg-$time-$pid"

        # Delete the log file if the build succeeded to prevent the directory
        # from filling very quickly with useless logs.
        [ "$KISS_KEEPLOG" = 1 ] || rm -f "$log_dir/$pkg-$time-$pid"

        # Copy the repository files to the package directory. This acts as the
        # database entry.
        cp -LRf "$repo_dir" "$pkg_dir/$pkg/$pkg_db/"

        run_hook post-build "$pkg" "$pkg_dir/$pkg"

        # Remove all .la files from the packages. They're unneeded and cause
        # issues when a package stops providing one. This recently caused an
        # issue with harfbuzz (See: 05096e5a4dc6db5d202342f538d067d87ae7135e).
        find "$pkg_dir/$pkg/usr/lib" -name \*.la -exec rm -f {} + 2>/dev/null ||:

        # Endless source of conflicts.
        rm -f "$pkg_dir/$pkg/usr/lib/charset.alias"

        # Create the manifest file early and make it empty. This ensures that
        # the manifest is added to the manifest.
        : > "$pkg_dir/$pkg/$pkg_db/$pkg/manifest"

        # Same for etcsums if /etc exists in package.
        [ -d "$pkg_dir/$pkg/etc" ] &&
            : > "$pkg_dir/$pkg/$pkg_db/$pkg/etcsums"

        pkg_strip    "$pkg"
        pkg_fix_deps "$pkg"
        pkg_manifest "$pkg"
        pkg_etcsums  "$pkg"
        pkg_tar      "$pkg"

        log "$pkg" "Successfully built package"

        # Install only dependencies of passed packages. If this is an update,
        # install the built package regardless.
        contains "$explicit" "$pkg" && [ -z "$pkg_update" ] && continue

        log "$pkg" "Needed as a dependency or has an update, installing"

        # False positive.
        # shellcheck disable=2030
        (
            KISS_FORCE=1
            args i "$pkg"
        )
    done

    log "Successfully built all packages"
}

pkg_checksums() {
    pkg_find "$1"

    [ -f "$repo_dir/sources" ] || return 0

    while read -r src _ || [ "$src" ]; do
        # Skip comments, blank lines and git sources.
        if [ -z "${src##\#*}" ] || [ -z "${src##git+*}" ]; then
            continue

        # Remote source.
        elif [ -z "${src##*://*}" ]; then
            sh256 "$src_dir/$1/${src##*/}"

        # Skip directories.
        elif [ -d "$repo_dir/$src" ] || [ -d "/$src" ]; then
            continue

        # Local file (relative).
        elif [ -f "$repo_dir/$src" ]; then
            sh256 "$repo_dir/$src"

        # Local file (absolute).
        elif [ -f "/$src" ]; then
            sh256 "/$src"
        fi
    done < "$repo_dir/sources" || die "$1" "Failed to generate checksums"
}

pkg_checksum_save() {
    # Generate and save checksums to file.
    pkg_find "$1"

    [ -f "$repo_dir/sources" ] ||
        return 0

    sums=$(pkg_checksums "$1")

    [ "$sums" ] || {
        log "$1" "Nothing to do"
        return 0
    }

    # False positive ('>> file' with no command).
    # shellcheck disable=2188
    printf '%s\n' "$sums" |

    if 2>/dev/null >> "$repo_dir/checksums"; then
        tee "$repo_dir/checksums"

    else
        log "$1" "Need permissions to generate checksums"
        file_owner "$repo_dir"
        as_root tee "$repo_dir/checksums"
    fi

    log "$1" "Generated checksums"
}

pkg_verify() {
    # Verify all package checksums. This is achieved by generating a new set
    # of checksums and then comparing those with the old set.
    pkg_find "$pkg"

    [ -f "$repo_dir/sources" ] ||
        return 0

    sum_sys=$(pkg_checksums "$pkg")

    [ "$sum_sys" ] ||
        return 0

    [ -f "$repo_dir/checksums" ] ||
        die "$pkg" "checksums file missing"

    sum_pkg=$(cut -b 1-64 < "$repo_dir/checksums")

    [ "$sum_sys" = "$sum_pkg" ] ||
        die "$pkg" "Checksum mismatch"
}

pkg_conflicts() {
    # Filter the tarball's manifest and select only files. Resolve all
    # symlinks in file paths as well.
    while read -r file; do
        file=$KISS_ROOT/${file#/}

        case $file in
            *[!/])
                cd -P "${file%/*}" 2>/dev/null ||
                    PWD=${file%/*}

                printf '%s\n' "${PWD#"$KISS_ROOT"}/${file##*/}"
            ;;
        esac
    done < "$tar_dir/$1/$pkg_db/$1/manifest" > "$tmp_dir/.manifest"

    set +f
    set -f "$sys_db"/*/manifest

    # Generate a list of all installed package manifests and remove the
    # current package from the list.
    for manifest do
        shift

        [ "$sys_db/$pkg/manifest" = "$manifest" ] &&
            continue

        set -- "$@" "$manifest"
    done

    [ "$#" != 0 ] || return 0

    # Store the list of found conflicts in a file for reuse.
    grep -Fxf "$tmp_dir/.manifest" -- "$@" 2>/dev/null \
        > "$tmp_dir/.conflicts" ||:

    if [ "$KISS_CHOICE" != 0  ] && [ -s "$tmp_dir/.conflicts" ]; then
        # Choices are dynamically created and destroyed.
        #
        # All file conflicts are installed to the choices directory
        # rather than their original destination. The package's
        # manifest is updated to reflect this.
        #
        # Swapping between choices just moves the locations of two
        # files around. The file in the system is copied to the
        # choices directory and the choice is moved to the system
        # (overwriting the remaining prior copy)
        while IFS=: read -r _ con; do
            printf 'Found conflict %s\n' "$con"

            # Create the "choices" directory inside of the tarball.
            # This directory will store the conflicting file.
            mkdir -p "$tar_dir/$pkg/${cho_dir:=var/db/kiss/choices}"

            # Construct the file name of the "db" entry of the
            # conflicting file. (pkg_name>usr>bin>ls)
            con_name=$(printf %s "$pkg$con" | sed 's|/|>|g')

            # Move the conflicting file to the choices directory
            # and name it according to the format above.
            mv -f "$tar_dir/$pkg/$con" \
                  "$tar_dir/$pkg/$cho_dir/$con_name" 2>/dev/null || {
                log "File must be in ${con%/*} and not a symlink to it"
                log "This can occur when a binary is installed to"
                log "/sbin instead of /usr/bin (example)"
                log "Before this file can be used as an alternative,"
                log "this must be fixed in $pkg. Contact the maintainer"
                die "by finding their details via kiss-maintainer" "" "!>"
            }
        done < "$tmp_dir/.conflicts"

        log "$pkg" "Converted all conflicts to choices (kiss a)"

        # Rewrite the package's manifest to update its location
        # to its new spot (and name) in the choices directory.
        pkg_manifest "$pkg" "$tar_dir" 2>/dev/null

    elif [ -s "$tmp_dir/.conflicts" ]; then
        log "Package '$pkg' conflicts with another package" "" "!>"
        log "Run 'KISS_CHOICE=1 kiss i $pkg' to add conflicts" "" "!>"
        die "as alternatives." "" "!>"
    fi
}

pkg_swap() {
    # Swap between package alternatives.
    pkg_list "$1" >/dev/null

    # pkg_name + /path/to/file -> pkg_name>path>to>file
    alt=$(
        printf %s "$1$2" |

        sed 's|/|>|g'
    )

    cd "$sys_db/../choices"

    if [ ! -f "$alt" ] && [ ! -h "$alt" ]; then
        die "Alternative '$1 $2' doesn't exist"

    elif [ -f "$2" ]; then
        # Figure out which package owns the file we are going to swap for
        # another package's. Print the full path to the manifest file which
        # contains the match to our search.
        set +f
        pkg_owner -lFx "$2" "$sys_db/"*/manifest ||
            die "File '$2' exists on filesystem but isn't owned"
        set -f

        # Convert the current owner to an alternative and rewrite its
        # manifest file to reflect this.
        cp -Pf "$KISS_ROOT/$2" "$pkg_owner>${alt#*>}"

        find_replace \
            "$2" \
            "${PWD#"$KISS_ROOT"}/$pkg_owner>${alt#*>}" \
            "../installed/$pkg_owner/manifest"
    fi

    # Convert the desired alternative to a real file and rewrite the manifest
    # file to reflect this. The reverse of above.
    mv -f "$alt" "$KISS_ROOT/$2"

    # Update the matching line in the manifest.
    find_replace \
        "${PWD#"$KISS_ROOT"}/$alt" \
        "$2" \
        "../installed/$1/manifest"

    printf '%s is now provided by %s (was %s)\n' "$2" "$1" "$pkg_owner"
}

pkg_install_files() {
    # Reverse the manifest file so that we start shallow and go deeper as we
    # iterate over each item. This is needed so that directories are created
    # going down the tree.
    sort "$2/$pkg_db/${2##*/}/manifest" |

    while read -r line; do
        [ -d "$KISS_ROOT/$line" ] || test "$1" "$KISS_ROOT/$line" &&
            continue

        rwx=$(ls -ld "$2/$line") oct='' b='' o=0

        # Convert the output of 'ls' (rwxrwx---) to octal. This is a
        # 1-9 loop with the second digit being the value of the field.
        for c in 14 22 31 44 52 61 74 82 91; do
            rwx=${rwx#?}

            case $rwx in
                [rwx]*): "$((o+=${c#?}))" ;;
                 [st]*): "$((o+=1))" "$((b+=4 / (${c%?}/3)))" ;;
                 [ST]*): "$((b+=1))" ;;
            esac

            case $((${c%?} % 3)) in
                0) oct=$oct$o o=0
            esac
        done

        # Copy files and create directories (preserving permissions).
        case $line in
            /etc/?*[!/])
                pkg_etc_file "$2" "${line#/}"
            ;;

            */)
                mkdir -m "$oct" "$KISS_ROOT/$line"
            ;;

            *)
                cp -fP "$2/$line" "$KISS_ROOT/$line"

                # This prepends $b which represents sticky bit,
                # setuid, setfgid, etc.
                [ -h "$KISS_ROOT/$line" ] ||
                    chmod "$b$oct" "$KISS_ROOT/$line"
            ;;
        esac
    done ||:

    pkg_etc_cnt=0
}

pkg_remove_files() {
    # Remove a file list from the system. This function runs during package
    # installation and package removal. Combining the removals in these two
    # functions allows us to stop duplicating code.
    while read -r file; do
        case $file in
            /etc/?*[!/])
                sum_sys=$(sh256 "$KISS_ROOT/$file") ||:
                sum_old=$(grep -F "$sum_sys" "$tmp_dir/.etcsums") ||:

                [ "$sum_sys" = "$sum_old" ] || {
                    printf 'Skipping %s (modified)\n' "$file"
                    continue
                }
            ;;
        esac 2>/dev/null

        file=$KISS_ROOT/$file

        # Remove files.
        if [ -f "$file" ] && [ ! -h "$file" ]; then
            rm -f "$file"

        # Remove file symlinks.
        elif [ -h "$file" ] && [ ! -d "$file" ]; then
            rm -f "$file"

        # Remove directories if empty.
        elif [ -d "$file" ] && [ ! -h "$file" ]; then
            rmdir "$file" 2>/dev/null ||:
        fi
    done ||:
}

pkg_etc_file() {
    pkg_etc_cnt=$((pkg_etc_cnt + 1))

    sum_new=$(sh256 "$1/$2")                                2>/dev/null ||:
    sum_sys=$(cd "$KISS_ROOT/"; sh256 "$2")                 2>/dev/null ||:
    sum_old=$(awk "NR == $pkg_etc_cnt" "$tmp_dir/.etcsums") 2>/dev/null ||:

    # Use a case statement to easily compare three strings at
    # the same time. Pretty nifty.
    case ${sum_old:-null}${sum_sys:-null}${sum_new} in
        # old = Y, sys = X, new = Y
        "${sum_new}${sum_sys}${sum_old}")
            return 0
        ;;

        # old = X, sys = X, new = X
        # old = X, sys = Y, new = Y
        # old = X, sys = X, new = Y
        "${sum_old}${sum_old}${sum_old}"|\
        "${sum_old:-null}${sum_sys}${sum_sys}"|\
        "${sum_sys}${sum_old}"*)
            new=
        ;;

        # All other cases.
        *)
            printf 'Saving /%s as /%s.new\n' "$2" "$2"
            new=.new
        ;;
    esac

    cp -fP "$1/$2" "$KISS_ROOT/${2}${new}"
}

pkg_remove() {
    # Remove a package and all of its files. The '/etc' directory is handled
    # differently and configuration files are *not* overwritten.
    pkg_list "$1" >/dev/null

    # False positive.
    # shellcheck disable=2031
    [ "$KISS_FORCE" = 1 ] || {
        log "$1" "Checking for reverse dependencies"

        (
            cd "$sys_db"
            set +f
            grep -lFx "$1" -- */depends

        ) && die "$1" "Can't remove package, others depend on it"
    }

    # Block being able to abort the script with 'Ctrl+C' during removal.
    # Removes all risk of the user aborting a package removal leaving an
    # incomplete package installed.
    trap '' INT

    if [ -x "$sys_db/$1/pre-remove" ]; then
        log "$1" "Running pre-remove script"
        "$sys_db/$1/pre-remove" ||:
    fi

    # Make a backup of the etcsums file (if it exists).
    cp -f "$sys_db/$1/etcsums" "$tmp_dir/.etcsums" 2>/dev/null ||:

    log "$1" "Removing package"
    pkg_remove_files < "$sys_db/$1/manifest"

    # Reset 'trap' to its original value. Removal is done so
    # we no longer need to block 'Ctrl+C'.
    trap pkg_clean EXIT INT

    log "$1" "Removed successfully"
}

pkg_install() {
    # Install a built package tarball.
    #
    # 1. Install package overwriting any existing files.
    # 2. Diff old manifest against new one and remove any files which exist in
    #    the old instance of the package but not the new one.
    # 3. Install package again, verifying all files and repairing any damage
    #    done by #2.

    # Handle tarball vs cache lookup (pkg_cache).
    if [ -z "${1%%*.tar.*}" ] && [ -f "$1" ]; then
        tar_file=$1 pkg=${1##*/} pkg=${pkg%#*}

    elif ! pkg_cache "$1" 2>/dev/null; then
        case $1 in
            *.tar.*) die "Tarball '$1' does not exist" ;;
            *)       die "Package '$1' has not yet been built"
        esac
    fi

    mkdir -p "$tar_dir/$pkg"
    cd       "$tar_dir/$pkg"

    decompress "$tar_file" | tar xf -

    [ -f "./$pkg_db/$pkg/manifest" ] ||
        die "Not a valid KISS package"

    # False positive.
    # shellcheck disable=2031
    [ "$KISS_FORCE" = 1 ] || {
        pkg_manifest_verify "$pkg_db/$pkg/manifest"

        [ -f "$pkg_db/$pkg/depends" ] && {
            while read -r dep dep_type || [ "$dep" ]; do
                case "$dep ${dep_type:-null}" in
                    [!#]*\ null)
                        pkg_list "$dep" >/dev/null 2>&1 ||
                            dep_err="$dep_err$dep, "
                    ;;
                esac
            done < "$pkg_db/$pkg/depends"

            [ -z "$dep_err" ] ||
                die "$pkg" "Missing ${dep_err%, }"
        }
    }

    run_hook pre-install "$pkg" "$tar_dir/$pkg"
    pkg_conflicts "$pkg"

    # Block Ctrl+C during installation.
    trap '' INT

    # If the package is already installed (and this is an upgrade) make a
    # backup of the manifest and etcsums files.
    cp -f "$sys_db/$pkg/manifest" "$tmp_dir/.manifest" 2>/dev/null ||:
    cp -f "$sys_db/$pkg/etcsums"  "$tmp_dir/.etcsums"  2>/dev/null ||:

    log "$pkg" "Installing package"
    pkg_install_files -z "$tar_dir/$pkg"

    grep -vFxf "$sys_db/$pkg/manifest" "$tmp_dir/.manifest" 2>/dev/null |
        pkg_remove_files

    log "$pkg" "Verifying installation"
    pkg_install_files -e "$tar_dir/$pkg"

    trap pkg_clean EXIT INT

    if [ -x "$sys_db/$pkg/post-install" ]; then
        log "$pkg" "Running post-install hook"

        hook_output=$("$sys_db/$pkg/post-install" 2>&1)

        [ -z "$hook_output" ] || {
            log "$pkg" "Running post-install hook" 2>&1
            printf '%s\n' "$hook_output"
        } |

        # 'tee' is used as we would still like to display 'stderr'
        tee -a "$log_dir/post-install-$time-$pid" >/dev/null
    fi

    run_hook post-install "$pkg" "$sys_db/$pkg"

    log "$pkg" "Installed successfully"
}

pkg_updates() {
    # Check all installed packages for updates. So long as the installed
    # version and the version in the repositories differ, it's considered
    # an update.
    log "Updating repositories"

    # Create a list of all repositories.
    # Intentional behavior.
    # shellcheck disable=2031,2046,2086
    {
        IFS=:
        set -- $KISS_PATH
        unset IFS
    }

    # Update each repository in '$KISS_PATH'.
    for repo do
        cd "$repo"

        case $(git remote 2>/dev/null) in
            "")
                log "$repo" " "
                printf 'Skipping git pull, not a repository\n'
            ;;

            *)
                cd "$(git rev-parse --show-toplevel)"
                git_root=$(git rev-parse --show-superproject-working-tree)
                cd "${git_root:-.}"

                contains "$repos" "$PWD" || {
                    repos="$repos $PWD "

                    # Display a tick if signing is enabled for this repository.
                    case $(git config merge.verifySignatures) in
                        true) log "$PWD" "[signed] " ;;
                        *)    log "$PWD" " " ;;
                    esac

                    if [ -w "$PWD" ] && [ "$uid" != 0 ]; then
                        git pull
                        git submodule update --remote --init -f

                    else
                        [ "$uid" = 0 ] || log "$PWD" "Need root to update"

                        # Find out the owner of the repository and spawn
                        # git as this user below.
                        #
                        # This prevents 'git' from changing the original
                        # ownership of files and directories in the rare
                        # case that the repository is owned by a 3rd user.
                        (
                            file_owner "$PWD"

                            # We're in a repository which is owned by a 3rd
                            # user. Not root or the current user.
                            [ "$user" = root ] ||
                                log "Dropping to $user for pull"

                            # Nesting is deep and line is long.
                            git_cmd="
                        git pull && git submodule update --remote --init -f
                            "

                            # 'su' requires that command be quoted.
                            case $su in *su)
                                git_cmd="'$git_cmd'"
                            esac

                            as_root sh -c "$git_cmd"
                        )
                    fi
                }
            ;;
        esac

        if [ -x update ]; then
            log "$PWD" "Running update hook"
            ./update
        fi
    done

    log "Checking for new package versions"

    set +f --

    for _pkg in "$sys_db/"*; do
        pkg_find "${_pkg##*/}"

        read -r db_ver db_rel < "$_pkg/version"
        read -r re_ver re_rel < "$repo_dir/version"

        [ "$db_ver-$db_rel" = "$re_ver-$re_rel" ] || {
            printf '%s %s-%s -> %s-%s\n' \
                "${_pkg##*/}" \
                "$db_ver" "$db_rel" \
                "$re_ver" "$re_rel"

            set -- "$@" "${_pkg##*/}"
        }
    done

    set -f

    contains "$*" kiss && {
        log "Detected package manager update"
        prompt "The package manager will be updated first"

        pkg_build kiss
        args i kiss

        log "Updated the package manager"
        log "Re-run 'kiss update' to update your system"

        exit 0
    }

    [ "$1" ] || {
        log "Everything is up to date"
        return
    }

    pkg_update=1
    pkg_build "$@"
}

pkg_clean() {
    # Clean up on exit or error. This removes everything related to the build.
    [ "$KISS_DEBUG" = 1 ] ||
        rm -rf "$tmp_dir"
}

args() {
    # Parse script arguments manually. This is rather easy to do in our case
    # since the first argument is always an "action" and the arguments that
    # follow are all package names.
    action=$1
    shift "$(($# != 0))"

    case $action in
        b|build|c|checksum|d|download|i|install|r|remove)
            [ "$1" ] || {
                # Intentional.
                # shellcheck disable=2031
                export KISS_PATH=${PWD%/*}:$KISS_PATH
                set -- "${PWD##*/}"
            }

            for arg do
                case $arg in
                    *'*'*|*'!'*|*'['*|*']'*|*' '*|*'	'*)
                        die "Argument contains: '!*[ \t]' ($arg)"
                    ;;
                esac
            done
        ;;
    esac

    # Rerun the script as root with a fixed environment if needed. We sadly
    # can't run singular functions as root so this is needed.
    #
    # False positive.
    # shellcheck disable=2031
    case $action in
        a|alternatives|i|install|r|remove)
            [ -z "$1" ] || [ -w "$KISS_ROOT/" ] || [ "$uid" = 0 ] || {
                as_root HOME="$HOME" \
                        XDG_CACHE_HOME="$XDG_CACHE_HOME" \
                        KISS_CHOICE="$KISS_CHOICE" \
                        KISS_COLOR="$KISS_COLOR" \
                        KISS_FORCE="$KISS_FORCE" \
                        KISS_PATH="$KISS_PATH" \
                        KISS_PID="$KISS_PID" \
                        KISS_ROOT="$KISS_ROOT" \
                        KISS_TMPDIR="$KISS_TMPDIR" \
                        "$0" "$action" "$@"

                return
            }
        ;;
    esac

    # Actions can be abbreviated to their first letter. This saves keystrokes
    # once you memorize the commands.
    case $action in
        a|alternatives)
            case $1 in
                -)
                    while read -r pkg path; do
                        pkg_swap "$pkg" "$path"
                    done
                ;;

                '')
                    set +f

                    # Go over each alternative and format the file
                    # name for listing. (pkg_name>usr>bin>ls)
                    for pkg in "$sys_db/../choices"/*; do
                        printf '%s\n' "${pkg##*/}"
                    done |

                    sed 's|>| /|; s|>|/|g; /\*/d'
                ;;

                *)
                    pkg_swap "$1" "$2"
                ;;
            esac
        ;;

        b|build)
            pkg_build "${@:?No packages installed}"
        ;;

        c|checksum)
            for pkg do
                pkg_lint "$pkg"
            done

            for pkg do
                pkg_sources "$pkg"
            done

            for pkg do
                pkg_checksum_save "$pkg"
            done
        ;;

        d|download)
            for pkg do
                pkg_sources "$pkg"
            done
        ;;

        i|install)
            for pkg do
                pkg_install "$pkg"
            done
        ;;

        l|list)
            pkg_list "$@"
        ;;

        r|remove)
            for pkg do
                pkg_remove "$pkg"
            done
        ;;

        s|search)
            for pkg do
                pkg_find "$pkg" '' all
            done
        ;;

        u|update)
            pkg_updates
        ;;

        v|version)
            printf '5.1.0\n'
        ;;

        '')
            log 'kiss [a|b|c|d|i|l|r|s|u|v] [pkg]...'
            log 'alternatives List and swap to alternatives'
            log 'build        Build a package'
            log 'checksum     Generate checksums'
            log 'download     Pre-download all sources'
            log 'install      Install a package'
            log 'list         List installed packages'
            log 'remove       Remove a package'
            log 'search       Search for a package'
            log 'update       Update the system'
            log 'version      Package manager version'

            printf '\nRun "kiss help-ext" to see all actions\n'
        ;;

        help-ext)
            log 'Extensions (kiss-* in PATH)'

            pkg_find kiss-\* "$PATH" all -x |

            while read -r file; do
                name=${file#*/kiss-}

                contains "$list" "$name" || {
                    list=" $list $name "

                    printf '%-15s ' "$name"
                    sed -n 's/^# *//;2p' "$file"
                }
            done
        ;;

        *)
            pkg_find "kiss-$action*" "$PATH" '' -x 2>/dev/null ||
                die "'kiss $action' is not a valid command"

            "$repo_dir" "$@"
        ;;
    esac

    if [ -s "$log_dir/post-install-$time-$pid" ]; then
        cat "$log_dir/post-install-$time-$pid"
        log "Post-install log stored to $log_dir/post-install-$time-$pid"
    fi
}

main() {
    # Globally disable globbing and enable exit-on-error.
    set -ef

    # Allow the user to disable colors in output via an environment variable.
    # Check this once so as to not slow down printing.
    [ "$KISS_COLOR" = 0 ] || {
        lcol='\033[1;33m'
        lcol2='\033[1;34m'
        lclr='\033[m'
    }

    # The PID of the current shell process is used to isolate directories
    # to each specific KISS instance. This allows multiple package manager
    # instances to be run at once. Store the value in another variable so
    # that it doesn't change beneath us.
    pid=${KISS_PID:-$$}

    # Catch errors and ensure that build files and directories are cleaned
    # up before we die. This occurs on 'Ctrl+C' as well as success and error.
    trap pkg_clean EXIT INT

    # Figure out which 'sudo' command to use based on the user's choice or what
    # is available on the system.
    su=${KISS_SU:-"$(
        command -v sudo ||
        command -v doas ||
        command -v sls
    )"} || su=su

    # Figure out which utility is available to dump elf information.
    elf_cmd=${KISS_ELF:="$(
        command -v readelf      ||
        command -v eu-readelf   ||
        command -v llvm-readelf
    )"} || elf_cmd=ldd

    # Store the date and time of script invocation to be used as the name of
    # the log files the package manager creates uring builds.
    time=$(date +%Y-%m-%d-%H:%M)

    # Make note of the user's current ID to do root checks later on.
    # This is used enough to warrant a place here.
    uid=$(id -u)

    # Ensure that the KISS_ROOT doesn't end with a '/'.
    KISS_ROOT=${KISS_ROOT%"${KISS_ROOT##*[!/]}"}

    # Define some paths which we will then use throughout the script.
    sys_db=$KISS_ROOT/${pkg_db:=var/db/kiss/installed}

    # This allows for automatic setup of a KISS chroot and will
    # do nothing on a normal system.
    mkdir -p "$KISS_ROOT/" 2>/dev/null ||:

    # Create cache directories and define variables.
    mkdir -p \
        "${cac_dir:="${XDG_CACHE_HOME:-"${HOME:?HOME is null}/.cache"}/kiss"}" \
            "${src_dir:="$cac_dir/sources"}" \
            "${log_dir:="$cac_dir/logs"}" \
            "${bin_dir:="$cac_dir/bin"}" \
        "${tmp_dir:="${KISS_TMPDIR:="$cac_dir/proc"}/$pid"}" \
            "${mak_dir:="$tmp_dir/build"}" \
            "${pkg_dir:="$tmp_dir/pkg"}" \
            "${tar_dir:="$tmp_dir/extract"}"

    args "$@"
}

main "$@"
